@baseUrl = http://localhost:3000/api/users
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQxNTA4NzI4MjcxYzZkODE1YmZlMDAiLCJ1c2VybmFtZSI6InRlc3RhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2NjEzNDU4OSwiZXhwIjoxNzY2NzM5Mzg5fQ.eoaB9AmVuWD-P4qAlIizyc3qfQDYcQPkSdcTtNvcq1c

### ======================================
### Get all users (Admin only)
### ======================================
GET {{baseUrl}}
Authorization: Bearer {{adminToken}}
Accept: application/json


### ======================================
### Get user by ID (Admin only)
### ======================================
GET {{baseUrl}}/694503d3b5b0e363ebbeb335
Authorization: Bearer {{adminToken}}
Accept: application/json


### ======================================
### Update user (Admin only)
### ======================================
PUT {{baseUrl}}/694503d3b5b0e363ebbeb335
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "username": "updatedUsername",
  "email": "updated@email.com",
  "role": "admin"
}


### ======================================
### Delete user (Admin only)
### ======================================
DELETE {{baseUrl}}/6943f8c122840851cd2b4bbd
Authorization: Bearer {{adminToken}}
Accept: application/json
